# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1
    - CONFIG=osx_r_base3.5.1

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "fUMDCkXz/xKKWoKhOoeMbVBzEAZUF7hdweynTWCZb3yGtsT/JGJ0VQjlliaagR4ZDzRdagIUWXB1aqk4kfzLMIkKbCi8dN+wNKQOvNhORDF8YZJqu4dmxllo64ae9MN30gwGiS5c992XgvYUk7FK1+e2JYhT2I1EHQ40hB8bNvcseMFhfvxXE64Dxpn4F2sgFb7mmmS5JJhaJoEB1i7x1XDlnELmKWmK9tSsLbvCkze7XncJnO8NXxHn2aQyllezIk6BDuDsSw3i32YjXeUu8GoDup43wcKSF1GauxCr/bGhSAfhDVwfG+6ho9kQah5vegzEpWx+ewZBOTeQ49nmI0Cb0Ehl6LpWSSvjTQNY8kW/I768RiLrLKtv70tCzxH9gSrF9IJn9NQG6OGROPS20qJMYn4kA1k4kAC0g7CNgxkEO2qOtKQN2P/FbDelTOP8rc4i2BcSpvewjsgyN5uKMgg30Bv7FnP6jQHNgSm8vn/2j6510sr7fvq3tfn4/WYuO2dqA8wRajKwVnSQQyq5qx4sXN+WnaE0/WwxZ5/fwHlF2Ebi8la0Oexnu6G0UzzaOrB7oazs0EqeQViuOmdL+evp6rKFS2hnKq17PYnZiF2yWYO8GJlIeDzxAi5iO4t6vwkVFTcBsLE2EJ5wpfHzRsT6q18kX6ywXqOVxW6U/Uc="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
