appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: fUMDCkXz/xKKWoKhOoeMbVBzEAZUF7hdweynTWCZb3yGtsT/JGJ0VQjlliaagR4ZDzRdagIUWXB1aqk4kfzLMIkKbCi8dN+wNKQOvNhORDF8YZJqu4dmxllo64ae9MN30gwGiS5c992XgvYUk7FK1+e2JYhT2I1EHQ40hB8bNvcseMFhfvxXE64Dxpn4F2sgFb7mmmS5JJhaJoEB1i7x1XDlnELmKWmK9tSsLbvCkze7XncJnO8NXxHn2aQyllezIk6BDuDsSw3i32YjXeUu8GoDup43wcKSF1GauxCr/bGhSAfhDVwfG+6ho9kQah5vegzEpWx+ewZBOTeQ49nmI0Cb0Ehl6LpWSSvjTQNY8kW/I768RiLrLKtv70tCzxH9gSrF9IJn9NQG6OGROPS20qJMYn4kA1k4kAC0g7CNgxkEO2qOtKQN2P/FbDelTOP8rc4i2BcSpvewjsgyN5uKMgg30Bv7FnP6jQHNgSm8vn/2j6510sr7fvq3tfn4/WYuO2dqA8wRajKwVnSQQyq5qx4sXN+WnaE0/WwxZ5/fwHlF2Ebi8la0Oexnu6G0UzzaOrB7oazs0EqeQViuOmdL+evp6rKFS2hnKq17PYnZiF2yWYO8GJlIeDzxAi5iO4t6vwkVFTcBsLE2EJ5wpfHzRsT6q18kX6ywXqOVxW6U/Uc=}
bot:
  automerge: true
